### ISSUE TITLE
It doesn't work on Octagon SF8008

### ISSUE THREAD

**Issue by jpuigs** [OpenVisionE2/BackupSuite#8]
On a Octagon SF8008 (twin SAT) it doesn't work.
git 467

No supported receiver found!
Image creation failed!

**Comment by persianpros** [comment]
Maybe we need to detect it via https://github.com/OpenVisionE2/BackupSuite/blob/master/plugin/backupsuite.sh

**Comment by jpuigs** [comment]
No, SatDreamGR

**Comment by persianpros** [comment]
Please test with Open Vision, you could test it with a test image: https://openvision.tech/?p=93

**Comment by nautilus7** [comment]
@persianpros what might be different in openvsion? I confirm that this box is not supported in latest satdreamgr (openpli based), so the same should be in openpli.

**Comment by georgeflu** [comment]
hello...
i own the first one combo sf8008 . i realized, that now in receivers info, there is an sf8008m .
by adding this "m" in second tab in the lookuptable.txt file, the backupsuite recognise the receiver, but now it shows... in the start 
"creating :kerneldumb 
cat : can't open '/sys/firmware/devicetree/base/choosen/kerneldev': No such file or directory" 
and finishing 
"creating : root.ubifsmv: can't rename '/hdd/bi/.bin' : no such file or directory"

finalizing, it creates the "rootfs.tar.bz2 " file in a correct size, and the "imageversion" file.
there is no "kernel.bin" file ...

**Comment by nautilus7** [comment]
@persianpros  issue is solved now with SatDreamGR, thanks!

**Comment by persianpros** [comment]
Your welcome :)
