### ISSUE TITLE
Compatibility with multilib images

### ISSUE THREAD

**Issue by nautilus7** [OpenVisionE2/BackupSuite#9]
Hi, would you consider removing all `/usr/lib/...` paths so the plugin becomes compatible with multilib images (that use `/usr/lib64/...`), without any tricks like symlinks etc. Thanks.

**Comment by persianpros** [comment]
Hello,

We have native multilib in Open Vision but even enigma2 should be fixed for this matter, simply use 'grep -ri "usr/lib"' in enigma2 and see for yourself.

But feel free to send us a PR :+1:

**Comment by nautilus7** [comment]
In enigma2 (openpli at least) there are about 12 cases where `/usr/lib/...` is used. And everyone is inside python code, so it's rather easy to fix.

BackupSuite has way more and apart from skins, they are found inside the .sh scripts, which is not so trivial to fix.

**Comment by persianpros** [comment]
Please take care of enigma2 first, I will update Backup Suite soon :+1:

**Comment by nautilus7** [comment]
Deal! Thanks.

**Comment by persianpros** [comment]
I hope it's ok now: https://github.com/OpenVisionE2/BackupSuite/commit/574a37900f611b09a09f5a97fb83cb2b23e0a3d3

**Comment by nautilus7** [comment]
You have a small typo and travis ci failed.

I will test later if it works. Thanks!

**Comment by persianpros** [comment]
I think it's ok now.

**Comment by persianpros** [comment]
What about xml files and skins?

**Comment by nautilus7** [comment]
@persianpros what xml files?

The skins are easy to fix.

You can either use the png's provided by the skin (recommended for colored buttons) like here: https://github.com/OpenVisionE2/BackupSuite/blob/master/plugin/schermen.py#L190
You can also use `buttons/red.png` or `buttons/key_red.png` which is  more common.

Or you can use the png's provided by the plugin, by setting the `self.skin_path` variable and writing paths relative to plugin's directory like this `~/img/red.png` like it is done here: 
https://github.com/OpenPLi/enigma2-plugins/blob/master/audiosync/src/AC3main.py#L22
https://github.com/OpenPLi/enigma2-plugins/blob/master/audiosync/src/AC3utils.py#L24


Regarding the 2boom plugin... Isn't it easy to fix or am I missing something?

https://github.com/OpenVisionE2/2boom-plugins/blob/master/epanel/src/tools.py#L2516 can be fixed like this:  `..., cmdlist = ["python %s" % resolveFilename(SCOPE_PLUGINS, "Extensions/epanel/no-ip.pyo")], ...` I guess it will work just fine.

For the other two cases, just use the `resloveFilename(SCOPE_PLUGINS, ...)` thingy like it is used in the lines right before the ones you linked to.

**Comment by nautilus7** [comment]
Oh, I forgot. I tested the BackupSuite fixes you made and it works ok now. Thanks.

**Comment by persianpros** [comment]
I'm not good with xml and skins so still I need your PR for "schermen.py" as it has hard-coded "/usr/lib" values.
